import type { Application, Request, Response } from 'express';
import rateLimit from 'express-rate-limit';
import { validate, schemas } from '../../middleware/validate.js';
import { StructuredLogger } from '../../utils/structured-logger.js';
import { AtomizerService } from '../../services/ingest/atomizer-service.js';
import { AtomicIngestService, type Compound } from '../../services/ingest/ingest-atomic-updated.js';
import { writeContentToMirror } from '../../services/mirror/write-content-to-mirror.js';
import { writeMirroredFile } from '../../services/mirror/mirror.js';

// Rate limiter for ingest endpoints
const ingestLimiter = rateLimit({
  windowMs: 60 * 1000, // 1 minute
  max: 10,
  message: { error: 'Too many ingest requests', retryAfter: 60 },
  standardHeaders: true,
  legacyHeaders: false,
  keyGenerator: (req: Request) => req.ip || req.socket.remoteAddress || 'unknown',
  skip: (req: Request) => {
    const isLocalhost = req.ip === '127.0.0.1' || req.ip === '::1' || req.ip?.startsWith('192.168.');
    if (isLocalhost && process.env.NODE_ENV === 'development') return true;
    return false;
  },
});

const apiLimiter = rateLimit({
  windowMs: 60 * 1000,
  max: 100,
  message: { error: 'Too many API requests', retryAfter: 60 },
  standardHeaders: true,
  legacyHeaders: false,
  keyGenerator: (req: Request) => req.ip || req.socket.remoteAddress || 'unknown',
});

// Ingestion endpoint (Atomic Architecture - Updated for Post-Migration)
export const setupIngestRoutes = (app: Application) => {
  app.use('/v1/ingest', ingestLimiter);

  // Ingestion endpoint (Atomic Architecture - Updated for Post-Migration)
  app.post('/v1/ingest', validate(schemas.ingest), async (req: Request, res: Response) => {
    const startTime = Date.now();
    try {
      const { content, source, type, bucket, buckets = [], tags = [] } = req.body;

      if (!content) {
        StructuredLogger.warn('INGEST_INVALID_REQUEST', { error: 'Content is required' });
        res.status(400).json({ error: 'Content is required' });
        return;
      }

      const provenanceType = (source && (source.includes('external') || source.includes('web'))) ? 'external' : 'internal';

      StructuredLogger.info('INGEST_REQUEST', {
        source: source || 'api_upload',
        content_length: content.length,
        buckets: buckets.length > 0 ? buckets : [bucket || 'notebook'],
      });

      // Use legacy Atomizer pipeline for performance
      const atomizer = new AtomizerService();
      const atomicIngest = new AtomicIngestService();

      const atomizeResult = await atomizer.atomize(
        content,
        source || 'api_upload',
        provenanceType as any, // Type assertion to bypass strict check
      );

      // Skip ingestion if transient data was detected
      if (!atomizeResult) {
        const result = {
          status: 'skipped',
          message: 'Content skipped (transient data detected)',
          id: null,
          duration_ms: Date.now() - startTime,
        };
        return res.json(result);
      }

      const { compound, molecules, atoms } = atomizeResult;

      // POST-MIGRATION UPDATE: Skip compound creation in database
      // The compounds table has been removed. We now write directly to molecules/atoms.
      
      // Extract provenance data from the compound object for use in molecules/atoms
      const compoundProvenance = compound.provenance || provenanceType;
      const compoundSignature = compound.molecular_signature;

      // Ingest result - store molecules and atoms directly (no compounds table)
      const compoundRef: Compound = {
        id: compound.id,
        path: compound.path!,
        timestamp: compound.timestamp || Date.now(),
        provenance: 'internal' as const,
        molecular_signature: '', // Will be generated by ingestion service
        molecules: [], // Empty - not needed for reference
        atoms: [] // Empty - will be populated during ingestion
      };

      await atomicIngest.ingestResult(
        compoundRef,
        molecules,
        atoms,
        buckets.length > 0 ? buckets : [bucket || 'notebook'],
        undefined, // provenance - handled internally
        undefined   // molecular signature - generated on ingestion
      );

      // Write content to mirror after successful DB storage (Pointer-Only Architecture)
      if (compound.path && content) {
        try {
          const ext = '.md';
          const safeId = compound.id.replace(/[^a-zA-Z0-9]/g, '-');
          const mirrorPath = `inbox/${Date.now()}_${safeId}.${ext}`;

          await writeContentToMirror(mirrorPath, content);

          // Update compound path to point to the mirror location
          compound.path = mirrorPath;

          StructuredLogger.info('MIRROR_WRITE', {
            path: mirrorPath,
            content_length: content.length,
            provenance: compoundProvenance,
          });
        } catch (mirrorError) {
          const error = mirrorError as Error;
          StructuredLogger.warn('MIRROR_WRITE_FAILED', {
            path: compound.path,
            error: error.message,
          });
        }
      }

      const duration = Date.now() - startTime;

      StructuredLogger.ingestion('success', {
        source: source || 'api_upload',
        compound_id: compound.id,
        atoms_count: atoms.length,
        molecules_count: molecules.length,
        buckets: buckets.length > 0 ? buckets : [bucket || 'notebook'],
        duration_ms: duration,
      });

      const result = {
        status: 'success',
        message: `Ingested ${atoms.length} atoms and ${molecules.length} molecules`,
        id: compound.id,
        duration_ms: duration,
      };

      res.status(200).json(result);
    } catch (e: any) {
      const duration = Date.now() - startTime;
      StructuredLogger.error('INGEST_ERROR', e, { source: req.body.source });
      
      // Return user-friendly error response
      res.status(500).json({ 
        error: 'Ingestion failed',
        details: e.message?.substring(0, 200) || 'Unknown error'
      });
    }
  });

  // Health check endpoint for ingestion service
  app.get('/v1/ingest/health', (req: Request, res: Response) => {
    res.json({ 
      status: 'healthy', 
      service: 'ingestion-api',
      timestamp: Date.now()
    });
  });
}